FROM python:3.12-slim


# Set the working directory in the container to /app
WORKDIR /app

# Install Python-dependecies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the code
COPY . .

# Expose port 5000
EXPOSE 5000

# When the container starts, run app.py with optional arguments
ENTRYPOINT ["python", "app.py"]