services:
  web:
    container_name: drunken-pictures
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "${FOLDER_PATH}:/images"
    command: ["/images"]

  ipcheck-host:
    image: alpine:latest
    # Only run when web is up
    depends_on:
      - web
    # Use host network mode
    network_mode: host
    # At start run ipcheck and exit
    entrypoint:
      - sh
      - -c
      - |
        echo "Flask is reachable at:"
        echo "  • http://localhost:5000"
        echo "  • http://host.docker.internal:5000"
    # Run once and exit
    restart: "no"